name: MyLineagePvpSystem
main: me.truekenny.MyLineagePvpSystem.MyLineagePvpSystem
version: 1.2.13
commands:
  pvpstatus:
    description: Displays user status.
    usage: "Usage: '/pvpstatus' to get user status"
  pvpspawn:
    description: Spawn mob.
    usage: "Usage: '/pvpspawn mobName [level [count]]', default level is auto assign"
  pvpsoe:
    description: Escape to spawn.
    usage: "Usage: '/pvpsoe', use Scroll of escape"
  pvpcall:
    description: Call player.
    usage: "Usage: '/pvpcall [player]' call player or '/pvpcall' teleport to caller"
