name: MyLineagePvpSystem
main: me.truekenny.MyLineagePvpSystem.MyLineagePvpSystem
version: 1.1.4
commands:
  pvpstatus:
    description: Displays user status.
    usage: "Usage: '/pvpstatus' to get user status"
  pvpspawn:
    description: Spawn mob.
    usage: "Usage: '/pvpspawn mobName [level [count]]', default level is auto assign"
