name: MyLineagePvpSystem
main: me.truekenny.MyLineagePvpSystem.MyLineagePvpSystem
version: 1.0.1
commands:
  pvpstatus:
    description: Displays user status.
    usage: "Usage: '/pvpstatus' to get user status"
